### ISSUE TITLE
Attach to existing HWND/NSView* 

### ISSUE THREAD

**Issue by m-hilgendorf** [dewf/openwl#1]
Coming over from the Reddit thread

It can be very useful for applications to create a window/view for extensions to attach to, but most windowing libraries expect to be the sole creator/owner of a window handle. To support this, the following method would be useful:

```
 wlWindow  wlAttach (void* platform_handle, int w, int h);
```
where the `void*` is one of: 
    
- X11 Window
- NSView*
- HWND 
- UIView*

**Comment by dewf** [comment]
Thanks again for bringing this to my attention. Like I said, I'll check it out tonight, because I would love for people to be able to write plugins 100% in the languages of their choice, including the GUI. I'll start looking at VST2 since that's what I'm most familiar with, then AudioUnits on the Mac side.

**Comment by dewf** [comment]
Tested with a minimal VST2 plugin on Windows, pretty straightforward. Ignore the API for now (as seen in `MyVSTEditor::open`) - just using the existing wlWindowCreate for now, will decide if it should be separated out or not.

demo video: https://webmshare.com/play/439E6

gist: https://gist.github.com/dewf/488937fa461696124ee96cea58eb523b

On to Cocoa, fingers crossed it's as straightforward  ....

**Comment by dewf** [comment]
Well, it's not nearly as straightforward on Mac, but at least I finally got the AU2 FilterDemo to build (but on 10.9 / Xcode 6.2 - I'll take it). The AU3 example seemed to require a developer certificate, which I neither have nor want ...

Anyhow, I can see where my own code needs to cough up its usually-internal NSView, and there's some other complications around that. Continuing to poke around...

**Comment by dewf** [comment]
So I managed to get it working for VST2 / AU2, which will hopefully work with VST3/AU3 as well.

I'll share the demo project I was using to test with in the next couple hours.

**Comment by dewf** [comment]
So here's the magic recipe for creating plugin windows:

On win32: 
[just this](https://github.com/dewf/wldlAudioPlugin/blob/63f67fd2ea44eaea33e016b4268b32f4bef43e25/win32_vst2/MyVSTPlugin.cpp#L126-L141
)

On Cocoa:
[step 1](https://github.com/dewf/wldlAudioPlugin/blob/63f67fd2ea44eaea33e016b4268b32f4bef43e25/cocoa_au2/AudioUnitEffectExample/Source/CocoaUI/AppleDemoFilter_OpenWLDL.mm#L14-L16)
[step 2](https://github.com/dewf/wldlAudioPlugin/blob/63f67fd2ea44eaea33e016b4268b32f4bef43e25/cocoa_au2/AudioUnitEffectExample/Source/CocoaUI/AppleDemoFilter_OpenWLDL.mm#L104-L116)

Long story short, there's a special wlInit flag on Cocoa to prevent the creation of a runloop - not necessary on win32 - and then both of them use a similar (but not identical) mechanism to instruct wlWindowCreate() to make a special kind of window.

Like I was saying, I could only get that AU example to work on OSX 10.9, and even then I had to manually symlink my OpenWL/DL libraries to /usr/local/lib, because I still haven't managed to include them in the app bundle in a working fashion. Point being, it's fragile so if you try to get it running even on 10.9, it will take some work.

I haven't touched Linux/LV2 support yet, but I'll get to it eventually if nobody else does. And re: UIViews, no plans for mobile at this time.
