### ISSUE TITLE
bindings for Java, Python, Ruby (etc)

### ISSUE THREAD

**Issue by paul-hammant** [dewf/openwl#16]
A ubiquitous cross-platform UI would be even better if it had bindings to Java, Python, Ruby and others available too :)

**Comment by dewf** [comment]
That's the idea! ... eventually.

But OpenWL/DL together only give you a top-level window that can be drawn into and interacted with. Whereas a proper GUI still needs to be built on top of that (with all the different types of controls / containers / etc).

My hope in contacting the various language communities (Nim, Rust, D, Zig so far) was to find people who want a GUI written in their own language (vs. GTK bindings), but don't have the time/interest/expertise to deal with the cross-platform native stuff. By abstracting that away, I made it possible for somebody to stick with a single language / single development platform, while still targeting Win/Mac/Linux. Additionally they could use whatever paradigm they want, not necessarily the oldschool hierarchy of widgets which I'm personally familiar with / a fan of.

Haven't found any takers yet, however.

In any event, I'm now working on my own GUI, written in D, for an application of my own. Assuming it reaches a level of maturity interesting to other people, what I'd like to do is create easy-to-use bindings for that GUI from other languages, because I personally don't like GTK very much and would like an alternative to Qt for non-C++ languages.

And as far as direct bindings to the lower-level OpenWL/DL, that's the easy part - it's just a bunch of C functions. If there's interest perhaps I can maintain a separate repository of FFI header files. But again, I don't think these libraries have a single user yet, so that's probably premature.

**Comment by paul-hammant** [comment]
What you're after is sorely needed. I've been tracking the "pseudo declarative" class if UI markup languages for 18 years and Flutter is going to beat QML there. Java's Swing is 20 years old now and super solid for convention UI creation*. I always wonder why since Java became open of sorts why Swing didn't get ported to a lower level OO language like D or C++, or indeed to any other HL language like Ruby or Python. Or Node for that matter, but Node.QML distracted me for a while - https://paulhammant.com/2017/04/08/node-qml-was-the-key-to-the-ubuntu-phones-success/. 

&ast; It is possible to do Swing in a pseudo-declarative way - https://github.com/paul-hammant/swing_component_testing/ - but that's unnatural to many, and comes with an inner class byte tax (200 bytes per inner class).

Maybe a patreon for what you're making?  Make an openwl org in GH now, and move the project to that (GH does the 302 redirects admirably), then make start the language bindings early - Ruby & Python first, in order to pull in motivated contributors.

**Comment by dewf** [comment]
I'm actually a big fan of Swing, and would have used it for the project which spun me off on this Sysiphean GUI detour ... except for some weird issues I was having when trying to host audio plugin UIs. Well, that and the more I poked around with it, the more I realized that it was a substandard experience on Mac (noticeably sluggish menus, for example). I even think its default visual styling, while hideous, is kind of endearing.

Incidentally, somebody partially ported SWT to D, but there's no Mac support and I happen to strongly dislike the SWT native widget paradigm.

Have you played with SwingBuilder for Groovy?

re: Patreon ... I've been keeping that in the back of my mind. But based on the complete lack of interest from the "novel languages" crowd (none of which has anything remotely as nice as, say, PyQt), I would be extremely surprised if any Python or Ruby programmers would have interest in building a new GUI from scratch (ie, directly atop OpenWL/DL). Or is there a demand there that I'm not seeing?

But most importantly, I really want to get back to my music app, because that was the whole reason for all of this, and it conveniently has the most realistic prospects for making money in the near-term. I'm quite pessimistic about the interest level in new desktop GUIs these days - people seem content to use Electron, if they're using the desktop at all.

**Comment by paul-hammant** [comment]
SwingBuilder? he he - https://paulhammant.com/blog/000218.html (2004). Groovy became non viable for that when they deleted their true interpreter.

TheDOM for fat UIs needs to die, IMO. My startup uses Flutter. I'd have preferred to have been using QML, but there's a push that's not happening there. I played with Swing in a Ruby app ten years ago https://paulhammant.com/blog/google-app-engine-for-java-with-rich-ruby-clients.html, but 'Swiby' didn't get traction however much I liked it. And _whytheluckystiff deleted his online presence and his Shoooes-app tech, and it never gained the same community when others undeleted it.

I've been using Intellij since 2001 and it uses Swing. My fist Java project used Swing (98) so I've never used SWT or felt the need to learn it. I wonder if a machine port of Swing's source to D would be possible. Or Rust. But now we have new puritanical rivalries between Rust, Zig, Nim and even Go. Maybe a machine port to all of those (except that some of them are not OO).

Funding/focus - I get that - super hard to solve.

**Comment by dewf** [comment]
Closing this issue because I don't feel these low level libraries are, in and of themselves, worth binding to from higher-level languages, UNLESS somebody is planning on making their own GUI from scratch - in which case, the effort required to implement the FFI definitions for these libraries is less than 1% of the total work involved.
